# Site settings
site: Nono Heryana
title: Mencari Jawaban, Menemukan Pertanyaan
keywords: blog
description: >-
  Kumpulan renungan seorang penikmat ilmu, <br>
  yang percaya otak bukan sekadar hiasan kepala.
lang: en-US
timezone:  Asia/Jakarta
repo: https://github.com/nonohry/nonoweb # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  nonohry

# Author settings
author:
  name: Nono Heryana
  bio: Dreamer
  picture: assets/images/profile.jpg 
  github: nonohry # github username
  twitter: SundaWiwitanID # twitter username
  facebook: nonohry # facebook username
  instagram: logikanono # instagram username
  youtube: https://www.youtube.com/ # youtube username
  linkedin: nonohry # linkedin username
  email: nonoheryana@gmail.com # email adress


# URL settings
url: "https://nono.my.id" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false